### ISSUE TITLE
Weird Compilation issue. Might be Fable 4 or Might be Solid / Vite

### ISSUE THREAD

**Issue by kunjee17** [alfonsogarciacaro/Feliz.Solid#1]
Hi, 

Here is how to reproduce the issue. 

Go to the project and run the project as it it should run. Once project is running go to `component.fs` file and change the name of any function / component. Desired behavior should be, **compilation error on terminal**. But here terminal is very much clean without any issue. and without any issue and also project will not work. You can actually see the error in browser console for jsx file.

**Comment by dstien** [comment]
Do the compilation output appear in your terminal if you add `clearScreen: false` in vite.config.js?

Like this:
```js
import { defineConfig } from 'vite';
import solidPlugin from 'vite-plugin-solid';

export default defineConfig({
  clearScreen: false,
  plugins: [solidPlugin()],
});
```

**Comment by kunjee17** [comment]
@dstien it do show file which it compiles but no error. Fable successfully compiles the file ( fs to jsx ) and hand it over to dev server. But as there is error in jsx file there will be no hmr and also error in console. Desire behavior should be error in terminal .

**Comment by alfonsogarciacaro** [comment]
Hmm, GH doesn't let me transfer the issue to Fable repo. I guess it's because it's in another org. I'll do it manually 👍
